name: Test case for issue 586
on: [push, pull_request, workflow_dispatch]
jobs:
  python:
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Double-check Python version
        run: |
          python --version
      - name: Clone Git repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python package
        run: |
          python -m pip install .
      - name: Run tests
        shell: powershell
        run: |
          python -c "import os, sys; print(f'PRE: stderr fd={sys.stderr.fileno()}'); import sounddevice; print(f'POST: stderr fd={sys.stderr.fileno()}'); sys.stderr.write('--- Attempting to write to stderr ---\n'); sys.stderr.flush(); os.write(sys.stderr.fileno(), b'--- OS level write ---\n'); 1/0"
